import React, { useState, useRef } from "react";
import { useWorkspace } from "../../context/WorkspaceContext";
import { useMembership } from "../../hooks/useMembership";
import {
  ASSET_DEFINITIONS,
  AssetDefinition,
  AssetCategory,
  assetsForPlan,
} from "../../domain/assetDefinitions";
import { STUDIO_PALETTES, paletteById, StudioPalette } from "../../domain/studioPalettes";
import { downloadBulkBundle, downloadSingleAsset } from "../../lib/exportEngine";
import {
  Sparkles,
  Download,
  Share2,
  Heart,
  CheckCircle,
  Eye,
  Sliders,
  FolderDown,
  Layers,
  RefreshCw,
  Edit3,
  X,
  Copy,
  ExternalLink,
} from "lucide-react";

const CATEGORIES: { key: string; label: string }[] = [
  { key: "ALL", label: "All Assets" },
  { key: "SOCIAL", label: "Social" },
  { key: "STREAMING", label: "Streaming" },
  { key: "MOTION", label: "Motion" },
  { key: "PRESS", label: "Press" },
  { key: "PRINT", label: "Print" },
  { key: "MERCH", label: "Merch" },
  { key: "COPY", label: "Copy" },
  { key: "WEB", label: "Web" },
];

export function CreativePackage({
  onNotify,
}: {
  onNotify: (m: string, t?: "success" | "info" | "error") => void;
}) {
  const { projects, releases, assets, createAsset } = useWorkspace();
  const { tier, can } = useMembership();

  const [selectedProjectId, setSelectedProjectId] = useState<string>(projects[0]?.id || "");
  const [activeCategory, setActiveCategory] = useState<string>("ALL");
  const [selectedPaletteId, setSelectedPaletteId] = useState<string>("cinematic-dark");
  const [searchQuery, setSearchQuery] = useState("");
  const [favorites, setFavorites] = useState<Record<string, boolean>>({});
  const [approvals, setApprovals] = useState<Record<string, boolean>>({});
  const [customTitles, setCustomTitles] = useState<Record<string, string>>({});
  const [previewAsset, setPreviewAsset] = useState<AssetDefinition | null>(null);
  const [isExporting, setIsExporting] = useState(false);
  const [exportProgress, setExportProgress] = useState(0);

  const currentProject =
    projects.find((p) => p.id === selectedProjectId) || projects[0] || null;
  const currentRelease =
    releases.find((r) => r.projectId === currentProject?.id) || releases[0] || null;

  const currentPalette: StudioPalette = paletteById(selectedPaletteId);

  // Asset definitions list based on membership
  const definitions = can("advanced_templates")
    ? ASSET_DEFINITIONS
    : assetsForPlan("free", "artist");

  const filteredAssets = definitions.filter((item) => {
    const matchesCat = activeCategory === "ALL" || item.category === activeCategory;
    const matchesSearch =
      !searchQuery ||
      item.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.category.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesCat && matchesSearch;
  });

  const toggleFavorite = (id: string) => {
    setFavorites((prev) => {
      const next = !prev[id];
      onNotify(next ? "Added to favorites" : "Removed from favorites", "info");
      return { ...prev, [id]: next };
    });
  };

  const toggleApproval = (id: string) => {
    setApprovals((prev) => {
      const next = !prev[id];
      onNotify(next ? "Asset approved" : "Approval revoked", "success");
      return { ...prev, [id]: next };
    });
  };

  // Render high-res asset to canvas and trigger download
  const handleDownloadAsset = (assetDef: AssetDefinition) => {
    const title = customTitles[assetDef.id] || currentProject?.title || "KEEDOHUB";
    const subtitle = currentRelease?.artistName || "Artist Release";

    if (assetDef.category === "COPY") {
      // Text download
      const copyContent = `${assetDef.name.toUpperCase()}\nProject: ${title}\nArtist: ${subtitle}\n\n[Content]\n${currentProject?.description || "Curated narrative statement by KeedoHub Studio."}\n\nGenerated by KeedoHub Creative Workspace.`;
      const blob = new Blob([copyContent], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${title}-${assetDef.id}.txt`;
      a.click();
      URL.revokeObjectURL(url);
      onNotify(`Exported ${assetDef.name}`, "success");
      return;
    }

    // Canvas image download
    const canvas = document.createElement("canvas");
    canvas.width = Math.min(assetDef.width, 3000);
    canvas.height = Math.min(assetDef.height, 3000);
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    // Background fill
    ctx.fillStyle = currentPalette.bg;
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    // Accent gradient / shapes
    const grad = ctx.createLinearGradient(0, 0, canvas.width, canvas.height);
    grad.addColorStop(0, currentPalette.bg);
    grad.addColorStop(0.5, currentPalette.bg2);
    grad.addColorStop(1, currentPalette.accent + "33");
    ctx.fillStyle = grad;
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    // Subtle geometric frame
    ctx.strokeStyle = currentPalette.accent;
    ctx.lineWidth = Math.max(2, Math.floor(canvas.width / 200));
    ctx.strokeRect(canvas.width * 0.05, canvas.height * 0.05, canvas.width * 0.9, canvas.height * 0.9);

    // Typography
    ctx.fillStyle = currentPalette.text;
    ctx.font = `bold ${Math.floor(canvas.width / 14)}px 'Space Grotesk', sans-serif`;
    ctx.textAlign = "center";
    ctx.fillText(title, canvas.width / 2, canvas.height * 0.45);

    ctx.fillStyle = currentPalette.sub;
    ctx.font = `500 ${Math.floor(canvas.width / 28)}px 'Plus Jakarta Sans', sans-serif`;
    ctx.fillText(subtitle, canvas.width / 2, canvas.height * 0.54);

    // Metadata watermark
    ctx.fillStyle = currentPalette.accent;
    ctx.font = `600 ${Math.floor(canvas.width / 40)}px monospace`;
    ctx.fillText(`KEEDOHUB // ${assetDef.name.toUpperCase()} // ${assetDef.width}x${assetDef.height}`, canvas.width / 2, canvas.height * 0.88);

    canvas.toBlob((blob) => {
      if (blob) {
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `${title}-${assetDef.id}.png`;
        a.click();
        URL.revokeObjectURL(url);
        onNotify(`Exported ${assetDef.name} (${assetDef.width}x${assetDef.height})`, "success");
      }
    }, "image/png");
  };

  // Bulk Package Export
  const handleBulkExport = async () => {
    if (!currentProject) {
      onNotify("Please select or create a project first.", "error");
      return;
    }
    setIsExporting(true);
    setExportProgress(10);

    try {
      const items = filteredAssets.map((a) => {
        const folder =
          a.category === "SOCIAL"
            ? "02-SOCIAL"
            : a.category === "STREAMING"
            ? "03-STREAMING"
            : a.category === "MOTION"
            ? "04-MOTION"
            : a.category === "PRESS"
            ? "05-PRESS"
            : a.category === "PRINT"
            ? "06-PRINT"
            : a.category === "MERCH"
            ? "07-MERCH"
            : a.category === "COPY"
            ? "08-COPY"
            : "01-ARTWORK";

        return {
          path: `${currentProject.title}/${folder}`,
          name: `${a.id}.${a.format === "txt" ? "txt" : "png"}`,
          body: `KEEDOHUB ASSET PACKAGE\nProject: ${currentProject.title}\nAsset: ${a.name}\nDimensions: ${a.width}x${a.height}\nFormat: ${a.format}\nPalette: ${currentPalette.name}\n\nCreated at KeedoHub Studio.`,
        };
      });

      setExportProgress(60);
      const res = downloadBulkBundle(currentProject.title, items);
      setExportProgress(100);
      onNotify(`Package exported: ${res.ok} assets bundled into organized folders.`, "success");
    } catch (err: unknown) {
      onNotify("Bulk export encountered an issue.", "error");
    } finally {
      setTimeout(() => {
        setIsExporting(false);
        setExportProgress(0);
      }, 600);
    }
  };

  return (
    <div className="mx-auto max-w-7xl px-4 py-6 space-y-6">
      {/* Studio Header & Project Bar */}
      <div className="rounded-3xl border border-zinc-800 bg-zinc-950/90 p-6 backdrop-blur-md shadow-xl">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2">
              <span className="text-[10px] font-bold tracking-[0.2em] text-red-500 uppercase">
                Studio Dashboard & Creative Customizer
              </span>
              <span className="rounded-full bg-zinc-800 px-2.5 py-0.5 text-[10px] font-semibold text-zinc-300">
                {definitions.length} Available Definitions
              </span>
            </div>
            <h1 className="mt-1 text-2xl md:text-3xl font-bold text-white tracking-tight">
              Creative Package {currentProject ? `— ${currentProject.title}` : ""}
            </h1>
            <p className="mt-1 text-xs text-zinc-400">
              Customize, approve, preview, and batch-export production-ready assets across Social, Streaming, Press, Print, and Motion.
            </p>
          </div>

          {/* Project & Palette Selectors */}
          <div className="flex flex-wrap items-center gap-2">
            <select
              value={selectedProjectId}
              onChange={(e) => setSelectedProjectId(e.target.value)}
              className="rounded-xl bg-zinc-900 border border-zinc-700 px-3 py-2 text-xs font-semibold text-white focus:border-red-500 focus:outline-none cursor-pointer"
            >
              {projects.map((p) => (
                <option key={p.id} value={p.id}>
                  Project: {p.title}
                </option>
              ))}
              {projects.length === 0 && <option value="">No projects</option>}
            </select>

            <select
              value={selectedPaletteId}
              onChange={(e) => setSelectedPaletteId(e.target.value)}
              className="rounded-xl bg-zinc-900 border border-zinc-700 px-3 py-2 text-xs font-semibold text-white focus:border-red-500 focus:outline-none cursor-pointer"
            >
              {STUDIO_PALETTES.map((pal) => (
                <option key={pal.id} value={pal.id}>
                  Palette: {pal.name}
                </option>
              ))}
            </select>

            <button
              onClick={handleBulkExport}
              disabled={isExporting || !currentProject}
              className="inline-flex items-center gap-1.5 rounded-xl bg-red-600 px-4 py-2 text-xs font-bold text-white hover:bg-red-500 transition-colors cursor-pointer shadow-md disabled:opacity-50"
            >
              <FolderDown className="w-3.5 h-3.5" />
              {isExporting ? `Exporting (${exportProgress}%)` : "Export Project Package"}
            </button>
          </div>
        </div>

        {/* Live Export Progress Bar if active */}
        {isExporting && (
          <div className="mt-4">
            <div className="flex justify-between text-[11px] font-semibold text-zinc-400 mb-1">
              <span>Generating production archive folders (01-ARTWORK to 08-COPY)...</span>
              <span>{exportProgress}%</span>
            </div>
            <div className="h-1.5 w-full overflow-hidden rounded-full bg-zinc-800">
              <div
                className="h-full bg-red-500 transition-all duration-300"
                style={{ width: `${exportProgress}%` }}
              />
            </div>
          </div>
        )}

        {/* Category Filters */}
        <div className="mt-6 flex flex-wrap items-center gap-1.5 border-t border-zinc-800/80 pt-4">
          {CATEGORIES.map((cat) => {
            const active = activeCategory === cat.key;
            return (
              <button
                key={cat.key}
                onClick={() => setActiveCategory(cat.key)}
                className={`rounded-xl px-3 py-1.5 text-xs font-bold transition-all cursor-pointer ${
                  active
                    ? "bg-red-600 text-white shadow-sm"
                    : "bg-zinc-900/70 text-zinc-400 hover:bg-zinc-800 hover:text-white"
                }`}
              >
                {cat.label}
              </button>
            );
          })}
        </div>
      </div>

      {/* Grid of Generated Creative Assets */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
        {filteredAssets.map((asset) => {
          const isFav = !!favorites[asset.id];
          const isAppr = !!approvals[asset.id];
          const displayTitle = customTitles[asset.id] || currentProject?.title || "KEEDOHUB";
          const displaySub = currentRelease?.artistName || "Release Artwork";

          return (
            <div
              key={asset.id}
              className="group flex flex-col justify-between overflow-hidden rounded-3xl border border-zinc-800 bg-zinc-950/70 hover:border-zinc-700 transition-all duration-200 shadow-sm"
            >
              {/* Asset Render Canvas Card */}
              <div
                className="relative flex aspect-square w-full items-center justify-center p-4 overflow-hidden select-none transition-transform duration-300 group-hover:scale-[1.01]"
                style={{ backgroundColor: currentPalette.bg }}
              >
                {/* Visual Backdrop Frame */}
                <div
                  className="absolute inset-2 rounded-2xl border border-white/10 flex flex-col items-center justify-center p-4 text-center"
                  style={{
                    backgroundColor: currentPalette.bg2,
                    boxShadow: "inset 0 0 20px rgba(0,0,0,0.5)",
                  }}
                >
                  <span
                    className="text-[9px] font-mono font-bold tracking-widest uppercase mb-1"
                    style={{ color: currentPalette.accent }}
                  >
                    {asset.category} · {asset.aspectRatio || "1:1"}
                  </span>
                  <h3
                    className="text-base md:text-lg font-bold tracking-tight line-clamp-2"
                    style={{ color: currentPalette.text }}
                  >
                    {displayTitle}
                  </h3>
                  <p
                    className="text-xs font-medium mt-1 truncate max-w-[85%]"
                    style={{ color: currentPalette.sub }}
                  >
                    {displaySub}
                  </p>

                  <div className="mt-3 flex items-center gap-1.5">
                    <span className="rounded-md bg-black/40 px-2 py-0.5 text-[9px] font-mono text-zinc-400">
                      {asset.width}×{asset.height}
                    </span>
                    <span className="rounded-md bg-black/40 px-2 py-0.5 text-[9px] font-mono text-zinc-400 uppercase">
                      {asset.format}
                    </span>
                  </div>
                </div>

                {/* Status Badges Overlay */}
                <div className="absolute top-3 left-3 flex gap-1">
                  {isAppr && (
                    <span className="flex items-center gap-1 rounded-full bg-emerald-500/90 backdrop-blur-md px-2 py-0.5 text-[9px] font-bold text-white shadow-sm">
                      <CheckCircle className="w-2.5 h-2.5" /> Approved
                    </span>
                  )}
                </div>

                {/* Quick Action Overlay on Hover */}
                <div className="absolute inset-0 bg-black/50 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-2 backdrop-blur-xs">
                  <button
                    onClick={() => setPreviewAsset(asset)}
                    className="rounded-full bg-white/10 border border-white/20 p-2.5 text-white hover:bg-white/20 transition-colors cursor-pointer"
                    title="Quick Preview"
                  >
                    <Eye className="w-4 h-4" />
                  </button>
                  <button
                    onClick={() => handleDownloadAsset(asset)}
                    className="rounded-full bg-red-600 p-2.5 text-white hover:bg-red-500 transition-colors cursor-pointer shadow-lg"
                    title="Download Asset"
                  >
                    <Download className="w-4 h-4" />
                  </button>
                </div>
              </div>

              {/* Card Meta & Control Bar */}
              <div className="p-4 space-y-3 bg-zinc-900/40 border-t border-zinc-800/60">
                <div className="flex items-start justify-between gap-2">
                  <div>
                    <h4 className="text-sm font-bold text-white truncate">{asset.name}</h4>
                    <p className="text-[11px] text-zinc-400 truncate">
                      {asset.description || `${asset.category} specification`}
                    </p>
                  </div>
                  <button
                    onClick={() => toggleFavorite(asset.id)}
                    className={`p-1 rounded-lg transition-colors cursor-pointer ${
                      isFav ? "text-red-500" : "text-zinc-500 hover:text-white"
                    }`}
                    title={isFav ? "Favorited" : "Add to favorites"}
                  >
                    <Heart className="w-4 h-4 fill-current" />
                  </button>
                </div>

                {/* Action Buttons Row */}
                <div className="flex items-center justify-between gap-1 pt-1">
                  <button
                    onClick={() => toggleApproval(asset.id)}
                    className={`flex items-center gap-1 rounded-xl px-2.5 py-1.5 text-[11px] font-semibold transition-colors cursor-pointer ${
                      isAppr
                        ? "bg-emerald-500/20 text-emerald-300 border border-emerald-500/30"
                        : "bg-zinc-800/80 text-zinc-400 hover:bg-zinc-700 hover:text-white"
                    }`}
                  >
                    <CheckCircle className="w-3 h-3" />
                    {isAppr ? "Approved" : "Approve"}
                  </button>

                  <div className="flex items-center gap-1">
                    <button
                      onClick={() => setPreviewAsset(asset)}
                      className="rounded-xl border border-zinc-700/60 bg-zinc-800/80 px-2.5 py-1.5 text-[11px] font-semibold text-zinc-300 hover:text-white cursor-pointer"
                    >
                      Customize
                    </button>
                    <button
                      onClick={() => handleDownloadAsset(asset)}
                      className="rounded-xl bg-red-600/90 hover:bg-red-500 p-1.5 text-white transition-colors cursor-pointer"
                      title="Download"
                    >
                      <Download className="w-3.5 h-3.5" />
                    </button>
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {filteredAssets.length === 0 && (
        <div className="rounded-3xl border border-zinc-800 bg-zinc-950/60 p-12 text-center">
          <Layers className="mx-auto w-10 h-10 text-zinc-600 mb-3" />
          <h3 className="text-base font-bold text-white">No assets match your filter</h3>
          <p className="text-xs text-zinc-500 mt-1">
            Try switching categories or clearing search keywords.
          </p>
        </div>
      )}

      {/* Single Asset Preview & Customizer Drawer / Modal */}
      {previewAsset && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4">
          <div className="relative w-full max-w-2xl rounded-3xl border border-zinc-800 bg-zinc-950 p-6 shadow-2xl space-y-5 max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between border-b border-zinc-800 pb-3">
              <div>
                <span className="text-[10px] font-bold text-red-500 uppercase tracking-widest">
                  Asset Customizer & Spec
                </span>
                <h3 className="text-lg font-bold text-white">{previewAsset.name}</h3>
              </div>
              <button
                onClick={() => setPreviewAsset(null)}
                className="rounded-xl border border-zinc-800 p-1.5 text-zinc-400 hover:text-white cursor-pointer"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Live Big Preview */}
            <div
              className="flex aspect-video w-full items-center justify-center rounded-2xl p-6 overflow-hidden border border-white/10"
              style={{ backgroundColor: currentPalette.bg }}
            >
              <div
                className="rounded-xl border border-white/10 p-6 text-center max-w-sm"
                style={{ backgroundColor: currentPalette.bg2 }}
              >
                <span
                  className="text-[10px] font-mono font-bold tracking-widest uppercase"
                  style={{ color: currentPalette.accent }}
                >
                  {previewAsset.category} · {previewAsset.width}×{previewAsset.height}
                </span>
                <h2
                  className="text-xl font-bold mt-2"
                  style={{ color: currentPalette.text }}
                >
                  {customTitles[previewAsset.id] || currentProject?.title || "KEEDOHUB"}
                </h2>
                <p className="text-xs mt-1" style={{ color: currentPalette.sub }}>
                  {currentRelease?.artistName || "Release Project"}
                </p>
              </div>
            </div>

            {/* Customization Inputs */}
            <div className="space-y-3">
              <div>
                <label className="block text-xs font-semibold text-zinc-300 mb-1">
                  Custom Asset Title / Headline
                </label>
                <input
                  type="text"
                  value={customTitles[previewAsset.id] || ""}
                  onChange={(e) =>
                    setCustomTitles({ ...customTitles, [previewAsset.id]: e.target.value })
                  }
                  placeholder={currentProject?.title || "Custom title"}
                  className="w-full rounded-xl bg-zinc-900 border border-zinc-700 px-3 py-2 text-sm text-white focus:border-red-500 focus:outline-none"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-semibold text-zinc-300 mb-1">
                    Output Dimensions
                  </label>
                  <p className="text-xs font-mono text-zinc-400 bg-zinc-900 border border-zinc-800 rounded-xl p-2.5">
                    {previewAsset.width} × {previewAsset.height} px
                  </p>
                </div>
                <div>
                  <label className="block text-xs font-semibold text-zinc-300 mb-1">
                    Output Format
                  </label>
                  <p className="text-xs font-mono text-zinc-400 bg-zinc-900 border border-zinc-800 rounded-xl p-2.5 uppercase">
                    {previewAsset.format} (Print & Web compliant)
                  </p>
                </div>
              </div>
            </div>

            {/* Footer Buttons */}
            <div className="flex items-center justify-between border-t border-zinc-800 pt-4">
              <button
                onClick={() => toggleApproval(previewAsset.id)}
                className={`flex items-center gap-1.5 rounded-xl px-4 py-2 text-xs font-bold transition-colors cursor-pointer ${
                  approvals[previewAsset.id]
                    ? "bg-emerald-500/20 text-emerald-300 border border-emerald-500/30"
                    : "bg-zinc-900 border border-zinc-700 text-zinc-300 hover:text-white"
                }`}
              >
                <CheckCircle className="w-4 h-4" />
                {approvals[previewAsset.id] ? "Approved for Delivery" : "Mark as Approved"}
              </button>

              <button
                onClick={() => {
                  handleDownloadAsset(previewAsset);
                  setPreviewAsset(null);
                }}
                className="inline-flex items-center gap-2 rounded-xl bg-red-600 px-5 py-2 text-xs font-bold text-white hover:bg-red-500 transition-colors cursor-pointer shadow-md"
              >
                <Download className="w-4 h-4" />
                Download High-Res
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
