import {
  IntegrationCategory,
  IntegrationProviderDefinition,
  IntegrationProviderId,
} from '../types';

export interface CategoryMetadata {
  id: IntegrationCategory;
  name: string;
  tagline: string;
  description: string;
  badge: string;
}

export const INTEGRATION_CATEGORIES: CategoryMetadata[] = [
  {
    id: 'social',
    name: 'Social Platforms',
    tagline: 'Multi-platform Distribution & Insights',
    description: 'Schedule content drops, monitor engagement trends, and sync audience reach across video and social networks.',
    badge: 'Content & Viral',
  },
  {
    id: 'music_dsp',
    name: 'Music & DSPs',
    tagline: 'Stream Telemetry & Catalog Delivery',
    description: 'Connect Spotify for Artists, Apple Music, and key DSPs to synchronize stream velocity, playlist adds, and release telemetry.',
    badge: 'Artist OS Core',
  },
  {
    id: 'cloud_storage',
    name: 'Cloud Storage & Vaults',
    tagline: 'High-Bitrate Stems & Production Assets',
    description: 'Directly ingest master WAVs, video ProRes files, and brand style guides from Google Drive, Dropbox, or AWS S3.',
    badge: 'Asset Pipeline',
  },
  {
    id: 'email_notifications',
    name: 'Email & Messaging',
    tagline: 'Fan & Customer Direct Communication',
    description: 'Deliver automated campaign newsletters, presave alerts, and transactional business receipts with enterprise delivery providers.',
    badge: 'Audience Direct',
  },
  {
    id: 'analytics',
    name: 'Analytics & Attribution',
    tagline: 'Conversion Funnels & Traffic Telemetry',
    description: 'Track presave conversions, website traffic, campaign ROI, and customer journey touchpoints with zero data leakage.',
    badge: 'Intelligence',
  },
  {
    id: 'payments',
    name: 'Payments & Revenue',
    tagline: 'Merch Checkout, Invoicing & Payouts',
    description: 'Safely connect Stripe, Paystack, or Flutterwave for global fan payments, brand licensing payouts, and splits disbursement.',
    badge: 'Monetization',
  },
];

export const INTEGRATION_PROVIDERS: IntegrationProviderDefinition[] = [
  // --- SOCIAL PLATFORMS ---
  {
    id: 'youtube',
    name: 'YouTube & Shorts',
    category: 'social',
    description: 'Sync video view performance, subscriber growth, and publish music visualizers directly to your official artist or brand channel.',
    icon: 'Youtube',
    accentColor: '#EF4444',
    authType: 'oauth2',
    supportsAutoSync: true,
    targetEntities: ['content', 'analytics'],
    docUrl: 'https://developers.google.com/youtube/v3',
    badge: 'OAuth 2.0 PKCE',
    availableScopes: [
      { id: 'youtube.readonly', name: 'Channel Insights', description: 'Read subscriber counts, views, retention curves, and engagement stats', isDefault: true },
      { id: 'youtube.upload', name: 'Direct Video Publishing', description: 'Schedule uploads for official visualizers and YouTube Shorts', isDefault: false },
    ],
  },
  {
    id: 'instagram',
    name: 'Instagram Professional',
    category: 'social',
    description: 'Sync Reels performance, follower demographics, and publish scheduled campaign carousels via Meta Graph API.',
    icon: 'Instagram',
    accentColor: '#EC4899',
    authType: 'oauth2',
    supportsAutoSync: true,
    targetEntities: ['content', 'analytics'],
    docUrl: 'https://developers.facebook.com/docs/instagram-api',
    badge: 'Meta Graph API',
    availableScopes: [
      { id: 'instagram_basic', name: 'Profile & Account Read', description: 'Access basic profile metadata and connected media', isDefault: true },
      { id: 'instagram_insights', name: 'Reach & Saves Metrics', description: 'Pull Reels performance, impressions, and follower growth', isDefault: true },
      { id: 'instagram_content_publish', name: 'Content Publishing', description: 'Publish pre-scheduled posts and reels to grid', isDefault: false },
    ],
  },
  {
    id: 'tiktok',
    name: 'TikTok for Creators & Business',
    category: 'social',
    description: 'Track sound usage virality, video view milestones, and sound analytics for release promo campaigns.',
    icon: 'Share2',
    accentColor: '#06B6D4',
    authType: 'oauth2',
    supportsAutoSync: true,
    targetEntities: ['content', 'analytics'],
    docUrl: 'https://developers.tiktok.com',
    badge: 'Creator API',
    availableScopes: [
      { id: 'user.info.stats', name: 'Account Analytics', description: 'Followers, video likes, and overall profile views', isDefault: true },
      { id: 'video.list', name: 'Video Performance Telemetry', description: 'Sound attribution and video completion retention rates', isDefault: true },
      { id: 'video.upload', name: 'Direct Post Publishing', description: 'Send approved drafts to TikTok Creator inbox', isDefault: false },
    ],
  },
  {
    id: 'meta_facebook',
    name: 'Meta / Facebook Pages & Ads',
    category: 'social',
    description: 'Connect official brand and artist pages for post synchronization, boosted post insights, and audience reach.',
    icon: 'Globe',
    accentColor: '#3B82F6',
    authType: 'oauth2',
    supportsAutoSync: true,
    targetEntities: ['campaign', 'analytics'],
    docUrl: 'https://developers.facebook.com',
    badge: 'Meta Suite',
    availableScopes: [
      { id: 'pages_read_engagement', name: 'Page Engagement Telemetry', description: 'View comments, reactions, and page impressions', isDefault: true },
      { id: 'read_insights', name: 'Audience Demographics', description: 'Country, city, and gender distribution analytics', isDefault: true },
      { id: 'pages_manage_posts', name: 'Publishing Permissions', description: 'Publish announcements and campaign updates', isDefault: false },
    ],
  },
  {
    id: 'twitter_x',
    name: 'X / Twitter API v2',
    category: 'social',
    description: 'Announce release dates, sync impressions and quote tweets, and manage community launch threads.',
    icon: 'Twitter',
    accentColor: '#F43F5E',
    authType: 'oauth2',
    supportsAutoSync: false,
    targetEntities: ['content', 'campaign'],
    docUrl: 'https://developer.x.com',
    badge: 'API v2',
    availableScopes: [
      { id: 'tweet.read', name: 'Timeline & Engagement Read', description: 'Track impressions, reposts, and quote engagements', isDefault: true },
      { id: 'users.read', name: 'Verified Account Verification', description: 'Confirm verified handle and follower milestones', isDefault: true },
      { id: 'tweet.write', name: 'Thread & Post Scheduling', description: 'Post release announcements directly from Keedohub', isDefault: false },
    ],
  },
  {
    id: 'linkedin',
    name: 'LinkedIn Company & Creator',
    category: 'social',
    description: 'Publish B2B announcements, press releases, brand partnerships, and founder thought leadership.',
    icon: 'Linkedin',
    accentColor: '#0EA5E9',
    authType: 'oauth2',
    supportsAutoSync: false,
    targetEntities: ['campaign', 'analytics'],
    docUrl: 'https://developer.linkedin.com',
    badge: 'Marketing Developer',
    availableScopes: [
      { id: 'r_liteprofile', name: 'Profile Identity Read', description: 'Access authorized brand identity and company page handle', isDefault: true },
      { id: 'rw_organization_admin', name: 'Company Page Telemetry', description: 'Engagement metrics and corporate post statistics', isDefault: true },
      { id: 'w_member_social', name: 'Direct Post Broadcast', description: 'Broadcast press announcements to feed', isDefault: false },
    ],
  },

  // --- MUSIC / DSP PLATFORMS ---
  {
    id: 'spotify',
    name: 'Spotify for Artists API',
    category: 'music_dsp',
    description: 'Stream velocity tracking, monthly listeners, editorial playlist detections, and automated presave routing.',
    icon: 'Radio',
    accentColor: '#10B981',
    authType: 'oauth2',
    supportsAutoSync: true,
    targetEntities: ['release', 'analytics'],
    docUrl: 'https://developer.spotify.com/documentation/web-api',
    badge: 'Verified DSP',
    availableScopes: [
      { id: 'user-read-playback-position', name: 'Stream Telemetry & Popularity', description: 'Pull algorithmic track popularity index and release telemetry', isDefault: true },
      { id: 'playlist-read-private', name: 'Playlist Placement Tracking', description: 'Detect additions to editorial, algorithmic, and user playlists', isDefault: true },
      { id: 'streaming-analytics', name: 'Audience Geographic Split', description: 'Top cities and listener retention analytics', isDefault: true },
    ],
  },
  {
    id: 'apple_music',
    name: 'Apple Music / MusicKit',
    category: 'music_dsp',
    description: 'Synchronize Apple Music catalog metadata, Shazam discovery trends, and spatial audio availability.',
    icon: 'Music',
    accentColor: '#F43F5E',
    authType: 'api_key',
    supportsAutoSync: true,
    targetEntities: ['release', 'analytics'],
    docUrl: 'https://developer.apple.com/musickit/',
    badge: 'MusicKit API',
    availableScopes: [
      { id: 'music-library-read', name: 'Catalog Verification', description: 'Check global ISRC matching and territory availability', isDefault: true },
      { id: 'catalog-insights', name: 'Shazam & City Charts', description: 'Track trending sound discovery across global markets', isDefault: true },
    ],
  },
  {
    id: 'audiomack',
    name: 'Audiomack Creators',
    category: 'music_dsp',
    description: 'Stream metrics, trending charts, and playlist placements across Afrobeats, Hip Hop, and emerging markets.',
    icon: 'Headphones',
    accentColor: '#F59E0B',
    authType: 'oauth2',
    supportsAutoSync: true,
    targetEntities: ['release', 'analytics'],
    docUrl: 'https://audiomack.com/data-api',
    badge: 'Emerging Markets',
    availableScopes: [
      { id: 'artist-stats-read', name: 'Stream & Favorite Metrics', description: 'Track plays, re-ups, downloads, and playlist features', isDefault: true },
      { id: 'audio-upload', name: 'Direct Catalog Delivery', description: 'Push approved audio assets to artist discography', isDefault: false },
    ],
  },
  {
    id: 'soundcloud',
    name: 'SoundCloud for Artists',
    category: 'music_dsp',
    description: 'Synchronize underground demo feedback, reposts, comments by second, and premiere private links.',
    icon: 'Radio',
    accentColor: '#F97316',
    authType: 'oauth2',
    supportsAutoSync: true,
    targetEntities: ['release', 'analytics'],
    docUrl: 'https://developers.soundcloud.com',
    badge: 'Community Stream',
    availableScopes: [
      { id: 'tracks.read', name: 'Track Performance Read', description: 'Playback counts, comments, and engagement rates', isDefault: true },
      { id: 'stats.read', name: 'Referral & Device Stats', description: 'Discover where listeners are playing demos', isDefault: true },
    ],
  },
  {
    id: 'youtube_music',
    name: 'YouTube Music & Content ID',
    category: 'music_dsp',
    description: 'Track art track stream numbers, official audio video claims, and Content ID royalty ingestion.',
    icon: 'Disc',
    accentColor: '#DC2626',
    authType: 'oauth2',
    supportsAutoSync: true,
    targetEntities: ['release', 'analytics'],
    docUrl: 'https://developers.google.com/youtube/partner',
    badge: 'Content ID Partner',
    availableScopes: [
      { id: 'youtube.partner', name: 'Content ID Claim Telemetry', description: 'Identify UGC videos monetizing your master recording', isDefault: true },
      { id: 'music-insights', name: 'Art Track Velocity', description: 'Daily plays from YouTube Music premium subscribers', isDefault: true },
    ],
  },

  // --- CLOUD STORAGE ---
  {
    id: 'google_drive',
    name: 'Google Drive for Enterprise',
    category: 'cloud_storage',
    description: 'Directly attach mix stems, EPK press folders, high-res photos, and contracts to Keedohub projects.',
    icon: 'HardDrive',
    accentColor: '#10B981',
    authType: 'oauth2',
    supportsAutoSync: true,
    targetEntities: ['content', 'release'],
    docUrl: 'https://developers.google.com/drive',
    badge: 'Secure File Picker',
    availableScopes: [
      { id: 'drive.file', name: 'Selected Asset Ingestion', description: 'View and open files created or opened by Keedohub', isDefault: true },
      { id: 'drive.readonly', name: 'Vault Folder Sync', description: 'Read metadata and preview images inside designated brand vaults', isDefault: false },
    ],
  },
  {
    id: 'dropbox',
    name: 'Dropbox Studio Vault',
    category: 'cloud_storage',
    description: 'Streamlined audio stem ingestion, lossless WAV mastering exchange, and revision review with collaborators.',
    icon: 'FolderArchive',
    accentColor: '#2563EB',
    authType: 'oauth2',
    supportsAutoSync: true,
    targetEntities: ['content', 'release'],
    docUrl: 'https://www.dropbox.com/developers',
    badge: 'Lossless Pipeline',
    availableScopes: [
      { id: 'files.content.read', name: 'File Preview & Download', description: 'Stream lossless master previews into Keedohub Player', isDefault: true },
      { id: 'files.content.write', name: 'Export Master Stems', description: 'Save rendered splits and mastered audio directly to Dropbox', isDefault: false },
    ],
  },
  {
    id: 'aws_s3',
    name: 'AWS S3 / Cloudflare R2',
    category: 'cloud_storage',
    description: 'Enterprise S3-compatible private bucket storage for high-throughput video masters and audio catalogs.',
    icon: 'Cloud',
    accentColor: '#F59E0B',
    authType: 'api_key',
    supportsAutoSync: true,
    targetEntities: ['content', 'release'],
    docUrl: 'https://aws.amazon.com/s3/',
    badge: 'Direct S3 Signed URLs',
    availableScopes: [
      { id: 's3:GetObject', name: 'Signed Download URL Generation', description: 'Read private media through time-limited pre-signed URLs', isDefault: true },
      { id: 's3:PutObject', name: 'Direct Multipart Upload', description: 'Bypass server limits with direct bucket uploads', isDefault: true },
    ],
  },

  // --- EMAIL & NOTIFICATIONS ---
  {
    id: 'resend',
    name: 'Resend Modern Email API',
    category: 'email_notifications',
    description: 'High-deliverability transactional emails for presave releases, VIP invite drops, and collaborator notices.',
    icon: 'Mail',
    accentColor: '#6366F1',
    authType: 'api_key',
    supportsAutoSync: false,
    targetEntities: ['campaign'],
    docUrl: 'https://resend.com/docs',
    badge: '99.9% Deliverability',
    availableScopes: [
      { id: 'emails.send', name: 'Broadcast & Transactional Dispatch', description: 'Send emails using authenticated domain DKIM/SPF', isDefault: true },
      { id: 'domains.verify', name: 'Domain Authentication Status', description: 'Verify custom domain DNS records and deliverability score', isDefault: true },
    ],
  },
  {
    id: 'sendgrid',
    name: 'Twilio SendGrid Marketing',
    category: 'email_notifications',
    description: 'Segmented audience campaigns, newsletter automation, open/click rate tracking, and bounce handling.',
    icon: 'Send',
    accentColor: '#0284C7',
    authType: 'api_key',
    supportsAutoSync: true,
    targetEntities: ['campaign', 'analytics'],
    docUrl: 'https://docs.sendgrid.com',
    badge: 'Marketing Engine',
    availableScopes: [
      { id: 'mail.send', name: 'Email Campaign Delivery', description: 'Dispatch bulk announcement emails to fan subscriber lists', isDefault: true },
      { id: 'stats.read', name: 'Open & Click Telemetry', description: 'Synchronize deliverability, opens, and link clicks to Keedohub Analytics', isDefault: true },
    ],
  },
  {
    id: 'postmark',
    name: 'Postmark by ActiveCampaign',
    category: 'email_notifications',
    description: 'Fastest transactional inbox delivery for password resets, invoice receipts, and split sheet signature alerts.',
    icon: 'CheckCircle2',
    accentColor: '#F59E0B',
    authType: 'api_key',
    supportsAutoSync: false,
    targetEntities: ['campaign'],
    docUrl: 'https://postmarkapp.com/developer',
    badge: 'Sub-Second Dispatch',
    availableScopes: [
      { id: 'server:outbound', name: 'Transactional Dispatch', description: 'Send priority transactional notifications', isDefault: true },
      { id: 'messages:read', name: 'Delivery Receipts', description: 'Verify inbound delivery logs and spam score validation', isDefault: false },
    ],
  },
  {
    id: 'twilio',
    name: 'Twilio SMS & WhatsApp',
    category: 'email_notifications',
    description: 'Direct-to-phone SMS drops and WhatsApp community broadcasts when new music or merch drops live.',
    icon: 'Smartphone',
    accentColor: '#EF4444',
    authType: 'api_key',
    supportsAutoSync: false,
    targetEntities: ['campaign'],
    docUrl: 'https://www.twilio.com/docs',
    badge: 'SMS / WhatsApp',
    availableScopes: [
      { id: 'sms.send', name: 'Global SMS Broadcast', description: 'Send high-urgency presave drop alerts via SMS', isDefault: true },
      { id: 'whatsapp.messages', name: 'WhatsApp Business API', description: 'Send formatted media messages and presave links', isDefault: false },
    ],
  },

  // --- ANALYTICS & ATTRIBUTION ---
  {
    id: 'google_analytics',
    name: 'Google Analytics 4 (GA4)',
    category: 'analytics',
    description: 'Connect GA4 Measurement Protocol to record EPK pageviews, presave link clicks, and merchandise conversions.',
    icon: 'BarChart3',
    accentColor: '#F59E0B',
    authType: 'api_key',
    supportsAutoSync: true,
    targetEntities: ['analytics', 'campaign'],
    docUrl: 'https://developers.google.com/analytics',
    badge: 'GA4 Measurement',
    availableScopes: [
      { id: 'analytics.readonly', name: 'Audience Traffic Read', description: 'Traffic sources, UTM referral campaigns, and geographic breakdown', isDefault: true },
      { id: 'analytics.provisioning', name: 'Server-Side Event Ingestion', description: 'Send conversion events directly without third-party cookie loss', isDefault: true },
    ],
  },
  {
    id: 'plausible',
    name: 'Plausible Privacy Analytics',
    category: 'analytics',
    description: 'Lightweight, 100% GDPR-compliant, cookie-less website analytics for EPKs, landing pages, and smart links.',
    icon: 'ShieldCheck',
    accentColor: '#8B5CF6',
    authType: 'api_key',
    supportsAutoSync: true,
    targetEntities: ['analytics'],
    docUrl: 'https://plausible.io/docs',
    badge: '100% GDPR Compliant',
    availableScopes: [
      { id: 'stats:read', name: 'Realtime Visitors & Referrers', description: 'Aggregated pageviews and referral domains with zero PII exposure', isDefault: true },
    ],
  },
  {
    id: 'mixpanel',
    name: 'Mixpanel Product Analytics',
    category: 'analytics',
    description: 'Funnel tracking from music presave discovery down to ticket checkout or digital download purchase.',
    icon: 'PieChart',
    accentColor: '#7C3AED',
    authType: 'api_key',
    supportsAutoSync: true,
    targetEntities: ['analytics', 'campaign'],
    docUrl: 'https://developer.mixpanel.com',
    badge: 'Funnel Telemetry',
    availableScopes: [
      { id: 'insights:export', name: 'Funnel Conversion Export', description: 'Inspect cohort retention and conversion steps', isDefault: true },
      { id: 'events:track', name: 'Server-Side Event Tracking', description: 'Record custom user milestone triggers', isDefault: true },
    ],
  },
  {
    id: 'meta_pixel',
    name: 'Meta Conversions API (CAPI)',
    category: 'analytics',
    description: 'Server-side conversion tracking for Facebook and Instagram ad campaigns with maximum attribution accuracy.',
    icon: 'Activity',
    accentColor: '#2563EB',
    authType: 'api_key',
    supportsAutoSync: false,
    targetEntities: ['campaign', 'analytics'],
    docUrl: 'https://developers.facebook.com/docs/marketing-api/conversions-api',
    badge: 'Server-Side CAPI',
    availableScopes: [
      { id: 'ads_management', name: 'Campaign Attribution Match', description: 'Match presave link clicks to ad sets for ROAS calculation', isDefault: true },
      { id: 'pixel_read', name: 'Conversion Event Telemetry', description: 'Audit server-side event match quality and health', isDefault: true },
    ],
  },

  // --- PAYMENTS & REVENUE ---
  {
    id: 'stripe',
    name: 'Stripe Connect & Checkout',
    category: 'payments',
    description: 'Accept credit cards, Apple Pay, and Google Pay worldwide for merchandise, album pre-orders, and licensing invoices.',
    icon: 'CreditCard',
    accentColor: '#6366F1',
    authType: 'oauth2',
    supportsAutoSync: true,
    targetEntities: ['campaign', 'analytics'],
    docUrl: 'https://stripe.com/docs',
    badge: 'PCI-DSS Level 1',
    sandboxAvailable: true,
    availableScopes: [
      { id: 'read_write', name: 'Checkout Sessions & Invoices', description: 'Create branded checkout sessions and process payments', isDefault: true },
      { id: 'invoices.read', name: 'Revenue & Payout History', description: 'Sync gross volume, platform fees, and net payout transfers', isDefault: true },
    ],
  },
  {
    id: 'paystack',
    name: 'Paystack Africa Direct',
    category: 'payments',
    description: 'Native African payments across Nigeria, Ghana, Kenya, and South Africa via Card, Bank Transfer, and Mobile Money.',
    icon: 'Coins',
    accentColor: '#059669',
    authType: 'api_key',
    supportsAutoSync: true,
    targetEntities: ['campaign', 'analytics'],
    docUrl: 'https://paystack.com/docs',
    badge: 'Mobile Money & Cards',
    sandboxAvailable: true,
    availableScopes: [
      { id: 'transactions.read', name: 'Transaction Settlement Telemetry', description: 'Verify payment statuses and bank transfer completions', isDefault: true },
      { id: 'subaccounts.manage', name: 'Automated Revenue Splits', description: 'Directly disburse percentage shares to producer bank accounts', isDefault: false },
    ],
  },
  {
    id: 'flutterwave',
    name: 'Flutterwave Global Africa',
    category: 'payments',
    description: 'Multi-currency payments in 30+ African currencies, MPESA, Barter, and global remittances for merch & live show tickets.',
    icon: 'Wallet',
    accentColor: '#F97316',
    authType: 'api_key',
    supportsAutoSync: true,
    targetEntities: ['campaign', 'analytics'],
    docUrl: 'https://developer.flutterwave.com',
    badge: 'Pan-African & Global',
    sandboxAvailable: true,
    availableScopes: [
      { id: 'charges.read', name: 'Charge & Settlement Sync', description: 'Synchronize ticket and merchandise revenue into campaign budget', isDefault: true },
      { id: 'transfers.read', name: 'Payout Confirmation', description: 'Verify contractor and collaborator payout receipts', isDefault: false },
    ],
  },
];

export function getProviderById(id: IntegrationProviderId): IntegrationProviderDefinition | undefined {
  return INTEGRATION_PROVIDERS.find((p) => p.id === id);
}

export function getProvidersByCategory(category: IntegrationCategory): IntegrationProviderDefinition[] {
  return INTEGRATION_PROVIDERS.filter((p) => p.category === category);
}
